version: '3.8'

services:
  mongodb:
    image: mongo
    container_name: mongodb
    ports:
      - "27017:27017"
    volumes:
      - mongoData2025:/data/db
    restart: unless-stopped
    # Opcionalmente, você pode adicionar variáveis de ambiente para configuração
    # environment:
    #   MONGO_INITDB_ROOT_USERNAME: root
    #   MONGO_INITDB_ROOT_PASSWORD: example

volumes:
  mongo2025:
    name: mongo2025