services:
  mongodb:
    image: mongo
    container_name: mongodb
    ports:
      - "27017:27017"
    volumes:
      - mongo2025:/data/db
    networks:
      - mynetwork
    restart: unless-stopped

  api:
    build:
      context: ./api
      dockerfile: Dockerfile
    container_name: api
    ports:
      - "3000:3000"
    depends_on:
      - mongodb
    networks:
      - mynetwork

  app-diario:
    build:
      context: ./app-diario
      dockerfile: Dockerfile
    container_name: app-diario
    ports:
      - "8080:8080"
    depends_on:
      - api
    networks:
      - mynetwork

volumes:
  mongo2025:
    name: mongo2025

networks:
  mynetwork:
    driver: bridge